# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: Sam
      MONGO_INITDB_ROOT_PASSWORD: secretPassword

  ports: 
    2719:27017

  command: mongod
